source 'https://rubygems.org'

ruby '2.0.0'

gem 'togostanza'

gem 'unicorn'
gem 'rake'

group :development do
  gem 'mina', require: false
end

group :test do
  gem 'rspec'
  gem 'capybara'
end

gem 'variation_stanza', path: './variation_stanza'
gem 'environment_attributes_stanza', path: './environment_attributes_stanza'
gem 'environment_environmental_ontology_stanza', path: './environment_environmental_ontology_stanza'
gem 'environment_geographical_map_stanza', path: './environment_geographical_map_stanza'
gem 'environment_inhabitants_stanza', path: './environment_inhabitants_stanza'
gem 'environment_inhabitants_statistics_stanza', path: './environment_inhabitants_statistics_stanza'
gem 'environment_taxonomic_composition_stanza', path: './environment_taxonomic_composition_stanza'
gem 'gene_attributes_stanza', path: './gene_attributes_stanza'
gem 'geneset_stanza', path: './geneset_stanza'
gem 'geneset_entry_stanza', path: './geneset_entry_stanza'
gem 'genome_cross_references_stanza', path: './genome_cross_references_stanza'
gem 'genome_genomic_context_stanza', path: './genome_genomic_context_stanza'
gem 'genome_information_stanza', path: './genome_information_stanza'
gem 'genome_plot_stanza', path: './genome_plot_stanza'
gem 'lineage_information_stanza', path: './lineage_information_stanza'
gem 'nucleotide_sequence_stanza', path: './nucleotide_sequence_stanza'
gem 'organism_cross_references_stanza', path: './organism_cross_references_stanza'
gem 'organism_culture_collections_stanza', path: './organism_culture_collections_stanza'
gem 'organism_habitat_stanza', path: './organism_habitat_stanza'
gem 'organism_medium_information_stanza', path: './organism_medium_information_stanza'
gem 'organism_names_stanza', path: './organism_names_stanza'
gem 'organism_pathogen_information_stanza', path: './organism_pathogen_information_stanza'
gem 'organism_phenotype_stanza', path: './organism_phenotype_stanza'
gem 'protein_attributes_stanza', path: './protein_attributes_stanza'
gem 'protein_cross_references_stanza', path: './protein_cross_references_stanza'
gem 'protein_general_annotation_stanza', path: './protein_general_annotation_stanza'
gem 'protein_names_stanza', path: './protein_names_stanza'
gem 'protein_ontologies_stanza', path: './protein_ontologies_stanza'
gem 'protein_orthologs_stanza', path: './protein_orthologs_stanza'
gem 'protein_pfam_plot_stanza', path: './protein_pfam_plot_stanza'
gem 'protein_references_stanza', path: './protein_references_stanza'
gem 'protein_sequence_stanza', path: './protein_sequence_stanza'
gem 'protein_sequence_annotation_stanza', path: './protein_sequence_annotation_stanza'
gem 'taxonomy_ortholog_profile_stanza', path: './taxonomy_ortholog_profile_stanza'
gem 'organism_jbrowse_stanza', path: './organism_jbrowse_stanza'
gem 'genome_jbrowse_stanza', path: './genome_jbrowse_stanza'

# Phenotype
gem 'my_inf_stanza', path: './my_inf_stanza'
gem 'mpo_genus_stanza', path: './mpo_genus_stanza'
gem 'mpo_environment_stanza', path: './mpo_environment_stanza'
gem 'mpo_shape_stanza', path: './mpo_shape_stanza'
gem 'gmo_applied_spices_stanza', path: './gmo_applied_spices_stanza'
gem 'gmo_genus_stanza', path: './gmo_genus_stanza'
gem 'gmo_approximation_stanza', path: './gmo_approximation_stanza'
gem 'medium_components_stanza', path: './medium_components_stanza'

# nanostanza
gem 'environment_inhabitants_statistics_nano_stanza', path: './environment_inhabitants_statistics_nano_stanza'
gem 'environment_organism_distribution_on_ph_nano_stanza', path: './environment_organism_distribution_on_ph_nano_stanza'
gem 'environment_organism_distribution_on_temperature_nano_stanza', path: './environment_organism_distribution_on_temperature_nano_stanza'
gem 'environment_top_level_symbolic_image_nano_stanza', path: './environment_top_level_symbolic_image_nano_stanza'
gem 'gene_length_nano_stanza', path: './gene_length_nano_stanza'
gem 'organism_gc_nano_stanza', path: './organism_gc_nano_stanza'
gem 'organism_gene_number_nano_stanza', path: './organism_gene_number_nano_stanza'
gem 'organism_genome_size_nano_stanza', path: './organism_genome_size_nano_stanza'
gem 'organism_microbial_cell_shape_nano_stanza', path: './organism_microbial_cell_shape_nano_stanza'
gem 'organism_ph_nano_stanza', path: './organism_ph_nano_stanza'
gem 'organism_related_disease_nano_stanza', path: './organism_related_disease_nano_stanza'
gem 'protein_3d_structure_nano_stanza', path: './protein_3d_structure_nano_stanza'
gem 'protein_ec_number_nano_stanza', path: './protein_ec_number_nano_stanza'
gem 'protein_references_timeline_nano_stanza', path: './protein_references_timeline_nano_stanza'
