source 'https://rubygems.org'

gem 'bio-svgenes', '>= 0.3.3'
gem 'togostanza'
gem 'unicorn'
gem 'variation_stanza', path: './variation_stanza'
gem 'environment_attributes_stanza', path: './environment_attributes_stanza'
gem 'environment_environmental_ontology_stanza', path: './environment_environmental_ontology_stanza'
gem 'environment_geographical_map_stanza', path: './environment_geographical_map_stanza'
gem 'environment_inhabitants_stanza', path: './environment_inhabitants_stanza'
gem 'environment_inhabitants_statistics_stanza', path: './environment_inhabitants_statistics_stanza'
gem 'environment_taxonomic_composition_stanza', path: './environment_taxonomic_composition_stanza'
gem 'gene_attributes_stanza', path: './gene_attributes_stanza'
gem 'geneset_stanza', path: './geneset_stanza'
gem 'geneset_entry_stanza', path: './geneset_entry_stanza'
